apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: good-eatz-doctor-flask
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: good-eatz-system
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://github.com/eugeneshanga/CS490-DoctorPatientBackend
    path: good-eatz-doctor-flask
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
